name: send message to telegram
on:
  schedule:
  - cron: "0/10 * * * 1-5"
jobs:
  runIndex:
    name: run index
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '14'
    - run: node src/index.js

  
