name: test send css
on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: "0/10 * * * 1-5"
jobs:
  my_job:
    name: run index
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: node ./src/index.js
